# coding: utf-8

"""
    Uplimit Organization API

    This API is used to manage organizations within the Uplimit platform. For more information, please reach out to your Uplimit Enterprise contact.

    The version of the OpenAPI document: 2025-03-17
    Contact: hello@uplimit.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import re  # noqa: F401
import io
import warnings

from pydantic import validate_arguments, ValidationError

from typing_extensions import Annotated
from pydantic import Field, StrictStr, conint

from typing import Optional

from openapi_client.models.v1_create_user_post200_response import V1CreateUserPost200Response
from openapi_client.models.v1_create_user_post_request import V1CreateUserPostRequest
from openapi_client.models.v1_enroll_user_into_session_post200_response import V1EnrollUserIntoSessionPost200Response
from openapi_client.models.v1_enroll_user_into_session_post_request import V1EnrollUserIntoSessionPostRequest
from openapi_client.models.v1_get_user_information_email_address_or_user_id_get200_response import V1GetUserInformationEmailAddressOrUserIdGet200Response
from openapi_client.models.v1_list_active_users_get200_response import V1ListActiveUsersGet200Response
from openapi_client.models.v1_list_enrollments_in_session_get200_response import V1ListEnrollmentsInSessionGet200Response
from openapi_client.models.v1_toggle_user_activation_post_request import V1ToggleUserActivationPostRequest

from openapi_client.api_client import ApiClient
from openapi_client.api_response import ApiResponse
from openapi_client.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError
)


class UserApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_arguments
    def v1_create_user_post(self, v1_create_user_post_request : Optional[V1CreateUserPostRequest] = None, **kwargs) -> V1CreateUserPost200Response:  # noqa: E501
        """v1_create_user_post  # noqa: E501

        This API creates a new user account on Uplimit and enrolls the user into your organization. If a user account with the same email already exists, we will just enroll that existing user into your organization.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.v1_create_user_post(v1_create_user_post_request, async_req=True)
        >>> result = thread.get()

        :param v1_create_user_post_request:
        :type v1_create_user_post_request: V1CreateUserPostRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: V1CreateUserPost200Response
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the v1_create_user_post_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.v1_create_user_post_with_http_info(v1_create_user_post_request, **kwargs)  # noqa: E501

    @validate_arguments
    def v1_create_user_post_with_http_info(self, v1_create_user_post_request : Optional[V1CreateUserPostRequest] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """v1_create_user_post  # noqa: E501

        This API creates a new user account on Uplimit and enrolls the user into your organization. If a user account with the same email already exists, we will just enroll that existing user into your organization.   # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.v1_create_user_post_with_http_info(v1_create_user_post_request, async_req=True)
        >>> result = thread.get()

        :param v1_create_user_post_request:
        :type v1_create_user_post_request: V1CreateUserPostRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(V1CreateUserPost200Response, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'v1_create_user_post_request'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method v1_create_user_post" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['v1_create_user_post_request'] is not None:
            _body_params = _params['v1_create_user_post_request']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['application/json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['bearerAuth']  # noqa: E501

        _response_types_map = {
            '200': "V1CreateUserPost200Response",
            '400': "V1CreateUserPost400Response",
            '401': "V1CreateUserPost400Response",
            '404': "V1CreateUserPost400Response",
            '405': "V1CreateUserPost400Response",
        }

        return self.api_client.call_api(
            '/v1/CreateUser', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def v1_enroll_user_into_session_post(self, v1_enroll_user_into_session_post_request : Optional[V1EnrollUserIntoSessionPostRequest] = None, **kwargs) -> V1EnrollUserIntoSessionPost200Response:  # noqa: E501
        """v1_enroll_user_into_session_post  # noqa: E501

        This API allows developers to add a user into a session. The user must have already been created with the Create User API (see above) before you can add this user.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.v1_enroll_user_into_session_post(v1_enroll_user_into_session_post_request, async_req=True)
        >>> result = thread.get()

        :param v1_enroll_user_into_session_post_request:
        :type v1_enroll_user_into_session_post_request: V1EnrollUserIntoSessionPostRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: V1EnrollUserIntoSessionPost200Response
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the v1_enroll_user_into_session_post_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.v1_enroll_user_into_session_post_with_http_info(v1_enroll_user_into_session_post_request, **kwargs)  # noqa: E501

    @validate_arguments
    def v1_enroll_user_into_session_post_with_http_info(self, v1_enroll_user_into_session_post_request : Optional[V1EnrollUserIntoSessionPostRequest] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """v1_enroll_user_into_session_post  # noqa: E501

        This API allows developers to add a user into a session. The user must have already been created with the Create User API (see above) before you can add this user.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.v1_enroll_user_into_session_post_with_http_info(v1_enroll_user_into_session_post_request, async_req=True)
        >>> result = thread.get()

        :param v1_enroll_user_into_session_post_request:
        :type v1_enroll_user_into_session_post_request: V1EnrollUserIntoSessionPostRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(V1EnrollUserIntoSessionPost200Response, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'v1_enroll_user_into_session_post_request'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method v1_enroll_user_into_session_post" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['v1_enroll_user_into_session_post_request'] is not None:
            _body_params = _params['v1_enroll_user_into_session_post_request']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['application/json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['bearerAuth']  # noqa: E501

        _response_types_map = {
            '200': "V1EnrollUserIntoSessionPost200Response",
            '400': "V1CreateUserPost400Response",
            '401': "V1CreateUserPost400Response",
            '404': "V1CreateUserPost400Response",
            '405': "V1CreateUserPost400Response",
        }

        return self.api_client.call_api(
            '/v1/EnrollUserIntoSession', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def v1_get_user_information_email_address_or_user_id_get(self, email_address_or_user_id : Annotated[StrictStr, Field(..., description="The email address or uplimit User ID of the user.")], **kwargs) -> V1GetUserInformationEmailAddressOrUserIdGet200Response:  # noqa: E501
        """v1_get_user_information_email_address_or_user_id_get  # noqa: E501

        This API allows developers to add a user into a session. The user must have already been created with the Create User API (see above) before you can add this user.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.v1_get_user_information_email_address_or_user_id_get(email_address_or_user_id, async_req=True)
        >>> result = thread.get()

        :param email_address_or_user_id: The email address or uplimit User ID of the user. (required)
        :type email_address_or_user_id: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: V1GetUserInformationEmailAddressOrUserIdGet200Response
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the v1_get_user_information_email_address_or_user_id_get_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.v1_get_user_information_email_address_or_user_id_get_with_http_info(email_address_or_user_id, **kwargs)  # noqa: E501

    @validate_arguments
    def v1_get_user_information_email_address_or_user_id_get_with_http_info(self, email_address_or_user_id : Annotated[StrictStr, Field(..., description="The email address or uplimit User ID of the user.")], **kwargs) -> ApiResponse:  # noqa: E501
        """v1_get_user_information_email_address_or_user_id_get  # noqa: E501

        This API allows developers to add a user into a session. The user must have already been created with the Create User API (see above) before you can add this user.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.v1_get_user_information_email_address_or_user_id_get_with_http_info(email_address_or_user_id, async_req=True)
        >>> result = thread.get()

        :param email_address_or_user_id: The email address or uplimit User ID of the user. (required)
        :type email_address_or_user_id: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(V1GetUserInformationEmailAddressOrUserIdGet200Response, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'email_address_or_user_id'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method v1_get_user_information_email_address_or_user_id_get" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['email_address_or_user_id'] is not None:
            _path_params['emailAddressOrUserId'] = _params['email_address_or_user_id']


        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['bearerAuth']  # noqa: E501

        _response_types_map = {
            '200': "V1GetUserInformationEmailAddressOrUserIdGet200Response",
            '400': "V1CreateUserPost400Response",
            '401': "V1CreateUserPost400Response",
            '404': "V1CreateUserPost400Response",
            '405': "V1CreateUserPost400Response",
        }

        return self.api_client.call_api(
            '/v1/GetUserInformation/{emailAddressOrUserId}', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def v1_list_active_users_get(self, skip : Optional[conint(strict=True, ge=0)] = None, take : Optional[conint(strict=True, ge=0)] = None, **kwargs) -> V1ListActiveUsersGet200Response:  # noqa: E501
        """v1_list_active_users_get  # noqa: E501

        This API lists all active users in your organization on the Uplimit platform.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.v1_list_active_users_get(skip, take, async_req=True)
        >>> result = thread.get()

        :param skip:
        :type skip: int
        :param take:
        :type take: int
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: V1ListActiveUsersGet200Response
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the v1_list_active_users_get_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.v1_list_active_users_get_with_http_info(skip, take, **kwargs)  # noqa: E501

    @validate_arguments
    def v1_list_active_users_get_with_http_info(self, skip : Optional[conint(strict=True, ge=0)] = None, take : Optional[conint(strict=True, ge=0)] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """v1_list_active_users_get  # noqa: E501

        This API lists all active users in your organization on the Uplimit platform.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.v1_list_active_users_get_with_http_info(skip, take, async_req=True)
        >>> result = thread.get()

        :param skip:
        :type skip: int
        :param take:
        :type take: int
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(V1ListActiveUsersGet200Response, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'skip',
            'take'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method v1_list_active_users_get" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('skip') is not None:  # noqa: E501
            _query_params.append(('skip', _params['skip']))

        if _params.get('take') is not None:  # noqa: E501
            _query_params.append(('take', _params['take']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['bearerAuth']  # noqa: E501

        _response_types_map = {
            '200': "V1ListActiveUsersGet200Response",
            '400': "V1CreateUserPost400Response",
            '401': "V1CreateUserPost400Response",
            '404': "V1CreateUserPost400Response",
            '405': "V1CreateUserPost400Response",
        }

        return self.api_client.call_api(
            '/v1/ListActiveUsers', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def v1_list_enrollments_in_session_get(self, uplimit_session_id : StrictStr, skip : Optional[conint(strict=True, ge=0)] = None, take : Optional[conint(strict=True, ge=0)] = None, **kwargs) -> V1ListEnrollmentsInSessionGet200Response:  # noqa: E501
        """v1_list_enrollments_in_session_get  # noqa: E501

        This API allows developers to list all active enrollments in a session.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.v1_list_enrollments_in_session_get(uplimit_session_id, skip, take, async_req=True)
        >>> result = thread.get()

        :param uplimit_session_id: (required)
        :type uplimit_session_id: str
        :param skip:
        :type skip: int
        :param take:
        :type take: int
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: V1ListEnrollmentsInSessionGet200Response
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the v1_list_enrollments_in_session_get_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.v1_list_enrollments_in_session_get_with_http_info(uplimit_session_id, skip, take, **kwargs)  # noqa: E501

    @validate_arguments
    def v1_list_enrollments_in_session_get_with_http_info(self, uplimit_session_id : StrictStr, skip : Optional[conint(strict=True, ge=0)] = None, take : Optional[conint(strict=True, ge=0)] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """v1_list_enrollments_in_session_get  # noqa: E501

        This API allows developers to list all active enrollments in a session.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.v1_list_enrollments_in_session_get_with_http_info(uplimit_session_id, skip, take, async_req=True)
        >>> result = thread.get()

        :param uplimit_session_id: (required)
        :type uplimit_session_id: str
        :param skip:
        :type skip: int
        :param take:
        :type take: int
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(V1ListEnrollmentsInSessionGet200Response, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'uplimit_session_id',
            'skip',
            'take'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method v1_list_enrollments_in_session_get" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('skip') is not None:  # noqa: E501
            _query_params.append(('skip', _params['skip']))

        if _params.get('take') is not None:  # noqa: E501
            _query_params.append(('take', _params['take']))

        if _params.get('uplimit_session_id') is not None:  # noqa: E501
            _query_params.append(('uplimitSessionId', _params['uplimit_session_id']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['bearerAuth']  # noqa: E501

        _response_types_map = {
            '200': "V1ListEnrollmentsInSessionGet200Response",
            '400': "V1CreateUserPost400Response",
            '401': "V1CreateUserPost400Response",
            '404': "V1CreateUserPost400Response",
            '405': "V1CreateUserPost400Response",
        }

        return self.api_client.call_api(
            '/v1/ListEnrollmentsInSession', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def v1_list_inactive_users_get(self, skip : Optional[conint(strict=True, ge=0)] = None, take : Optional[conint(strict=True, ge=0)] = None, **kwargs) -> V1ListActiveUsersGet200Response:  # noqa: E501
        """v1_list_inactive_users_get  # noqa: E501

        This API lists all inactive users in your organization on the Uplimit platform.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.v1_list_inactive_users_get(skip, take, async_req=True)
        >>> result = thread.get()

        :param skip:
        :type skip: int
        :param take:
        :type take: int
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: V1ListActiveUsersGet200Response
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the v1_list_inactive_users_get_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.v1_list_inactive_users_get_with_http_info(skip, take, **kwargs)  # noqa: E501

    @validate_arguments
    def v1_list_inactive_users_get_with_http_info(self, skip : Optional[conint(strict=True, ge=0)] = None, take : Optional[conint(strict=True, ge=0)] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """v1_list_inactive_users_get  # noqa: E501

        This API lists all inactive users in your organization on the Uplimit platform.  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.v1_list_inactive_users_get_with_http_info(skip, take, async_req=True)
        >>> result = thread.get()

        :param skip:
        :type skip: int
        :param take:
        :type take: int
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(V1ListActiveUsersGet200Response, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'skip',
            'take'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method v1_list_inactive_users_get" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        if _params.get('skip') is not None:  # noqa: E501
            _query_params.append(('skip', _params['skip']))

        if _params.get('take') is not None:  # noqa: E501
            _query_params.append(('take', _params['take']))

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # authentication setting
        _auth_settings = ['bearerAuth']  # noqa: E501

        _response_types_map = {
            '200': "V1ListActiveUsersGet200Response",
            '400': "V1CreateUserPost400Response",
            '401': "V1CreateUserPost400Response",
            '404': "V1CreateUserPost400Response",
            '405': "V1CreateUserPost400Response",
        }

        return self.api_client.call_api(
            '/v1/ListInactiveUsers', 'GET',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))

    @validate_arguments
    def v1_toggle_user_activation_post(self, v1_toggle_user_activation_post_request : Optional[V1ToggleUserActivationPostRequest] = None, **kwargs) -> V1EnrollUserIntoSessionPost200Response:  # noqa: E501
        """v1_toggle_user_activation_post  # noqa: E501

        This API changes whether a user is active in your organization (i.e. sets their state to activated or deactivated).  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.v1_toggle_user_activation_post(v1_toggle_user_activation_post_request, async_req=True)
        >>> result = thread.get()

        :param v1_toggle_user_activation_post_request:
        :type v1_toggle_user_activation_post_request: V1ToggleUserActivationPostRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: V1EnrollUserIntoSessionPost200Response
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the v1_toggle_user_activation_post_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.v1_toggle_user_activation_post_with_http_info(v1_toggle_user_activation_post_request, **kwargs)  # noqa: E501

    @validate_arguments
    def v1_toggle_user_activation_post_with_http_info(self, v1_toggle_user_activation_post_request : Optional[V1ToggleUserActivationPostRequest] = None, **kwargs) -> ApiResponse:  # noqa: E501
        """v1_toggle_user_activation_post  # noqa: E501

        This API changes whether a user is active in your organization (i.e. sets their state to activated or deactivated).  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.v1_toggle_user_activation_post_with_http_info(v1_toggle_user_activation_post_request, async_req=True)
        >>> result = thread.get()

        :param v1_toggle_user_activation_post_request:
        :type v1_toggle_user_activation_post_request: V1ToggleUserActivationPostRequest
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: tuple(V1EnrollUserIntoSessionPost200Response, status_code(int), headers(HTTPHeaderDict))
        """

        _params = locals()

        _all_params = [
            'v1_toggle_user_activation_post_request'
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers'
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method v1_toggle_user_activation_post" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}

        # process the query parameters
        _query_params = []
        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        if _params['v1_toggle_user_activation_post_request'] is not None:
            _body_params = _params['v1_toggle_user_activation_post_request']

        # set the HTTP header `Accept`
        _header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # set the HTTP header `Content-Type`
        _content_types_list = _params.get('_content_type',
            self.api_client.select_header_content_type(
                ['application/json']))
        if _content_types_list:
                _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['bearerAuth']  # noqa: E501

        _response_types_map = {
            '200': "V1EnrollUserIntoSessionPost200Response",
            '400': "V1CreateUserPost400Response",
            '401': "V1CreateUserPost400Response",
            '404': "V1CreateUserPost400Response",
            '405': "V1CreateUserPost400Response",
        }

        return self.api_client.call_api(
            '/v1/ToggleUserActivation', 'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get('_return_http_data_only'),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'))
