# coding: utf-8

"""
    Uplimit Organization API

    This API is used to manage organizations within the Uplimit platform. For more information, please reach out to your Uplimit Enterprise contact.

    The version of the OpenAPI document: 2025-08-11
    Contact: hello@uplimit.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.export_api import ExportApi  # noqa: E501


class TestExportApi(unittest.TestCase):
    """ExportApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ExportApi()

    def tearDown(self) -> None:
        self.api.api_client.close()

    def test_v1_get_learner_activity_get_get(self) -> None:
        """Test case for v1_get_learner_activity_get_get

        """
        pass

    def test_v1_get_learner_activity_start_post(self) -> None:
        """Test case for v1_get_learner_activity_start_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
