# coding: utf-8

"""
    Uplimit Organization API

    This API is used to manage organizations within the Uplimit platform. For more information, please reach out to your Uplimit Enterprise contact.

    The version of the OpenAPI document: 2025-03-07
    Contact: hello@uplimit.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.list_sessions_in_course_response_schema import ListSessionsInCourseResponseSchema  # noqa: E501

class TestListSessionsInCourseResponseSchema(unittest.TestCase):
    """ListSessionsInCourseResponseSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListSessionsInCourseResponseSchema:
        """Test ListSessionsInCourseResponseSchema
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListSessionsInCourseResponseSchema`
        """
        model = ListSessionsInCourseResponseSchema()  # noqa: E501
        if include_optional:
            return ListSessionsInCourseResponseSchema(
                sessions = [
                    openapi_client.models._v1_list_sessions_in_course_get_200_response_sessions_inner._v1_ListSessionsInCourse_get_200_response_sessions_inner(
                        uplimit_session_id = '', 
                        name = '', 
                        starts_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                total_count = 1.337
            )
        else:
            return ListSessionsInCourseResponseSchema(
                sessions = [
                    openapi_client.models._v1_list_sessions_in_course_get_200_response_sessions_inner._v1_ListSessionsInCourse_get_200_response_sessions_inner(
                        uplimit_session_id = '', 
                        name = '', 
                        starts_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                total_count = 1.337,
        )
        """

    def testListSessionsInCourseResponseSchema(self):
        """Test ListSessionsInCourseResponseSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
