# coding: utf-8

"""
    Uplimit Organization API

    This API is used to manage organizations within the Uplimit platform. For more information, please reach out to your Uplimit Enterprise contact.

    The version of the OpenAPI document: 2025-08-11
    Contact: hello@uplimit.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.v1_get_learner_activity_start_post200_response import V1GetLearnerActivityStartPost200Response  # noqa: E501

class TestV1GetLearnerActivityStartPost200Response(unittest.TestCase):
    """V1GetLearnerActivityStartPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1GetLearnerActivityStartPost200Response:
        """Test V1GetLearnerActivityStartPost200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1GetLearnerActivityStartPost200Response`
        """
        model = V1GetLearnerActivityStartPost200Response()  # noqa: E501
        if include_optional:
            return V1GetLearnerActivityStartPost200Response(
                job_id = ''
            )
        else:
            return V1GetLearnerActivityStartPost200Response(
                job_id = '',
        )
        """

    def testV1GetLearnerActivityStartPost200Response(self):
        """Test V1GetLearnerActivityStartPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
