# coding: utf-8

"""
    Uplimit Organization API

    This API is used to manage organizations within the Uplimit platform. For more information, please reach out to your Uplimit Enterprise contact.

    The version of the OpenAPI document: 2025-03-07
    Contact: hello@uplimit.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.enroll_user_into_course_schema import EnrollUserIntoCourseSchema  # noqa: E501

class TestEnrollUserIntoCourseSchema(unittest.TestCase):
    """EnrollUserIntoCourseSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EnrollUserIntoCourseSchema:
        """Test EnrollUserIntoCourseSchema
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EnrollUserIntoCourseSchema`
        """
        model = EnrollUserIntoCourseSchema()  # noqa: E501
        if include_optional:
            return EnrollUserIntoCourseSchema(
                email_address = '',
                session_id = '',
                uplimit_session_id = '',
                subscription_commitment_id = ''
            )
        else:
            return EnrollUserIntoCourseSchema(
                email_address = '',
        )
        """

    def testEnrollUserIntoCourseSchema(self):
        """Test EnrollUserIntoCourseSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
