# coding: utf-8

"""
    Uplimit Organization API

    This API is used to manage organizations within the Uplimit platform. For more information, please reach out to your Uplimit Enterprise contact.

    The version of the OpenAPI document: 2025-03-07
    Contact: hello@uplimit.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.toggle_user_activation_schema import ToggleUserActivationSchema  # noqa: E501

class TestToggleUserActivationSchema(unittest.TestCase):
    """ToggleUserActivationSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ToggleUserActivationSchema:
        """Test ToggleUserActivationSchema
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ToggleUserActivationSchema`
        """
        model = ToggleUserActivationSchema()  # noqa: E501
        if include_optional:
            return ToggleUserActivationSchema(
                email_address = '',
                set_is_active = True
            )
        else:
            return ToggleUserActivationSchema(
                email_address = '',
                set_is_active = True,
        )
        """

    def testToggleUserActivationSchema(self):
        """Test ToggleUserActivationSchema"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
