/**
 * Uplimit Organization API
 * This API is used to manage organizations within the Uplimit platform. For more information, please reach out to your Uplimit Enterprise contact.
 *
 * The version of the OpenAPI document: 2025-08-18
 * Contact: hello@uplimit.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class AddUserAuthenticationMethodSchema {
    /**
    * The email address of the user.
    */
    'emailAddress': string;
    /**
    * The authentication method to add to the user.
    */
    'authenticationMethod': AddUserAuthenticationMethodSchema.AuthenticationMethodEnum;
    /**
    * For SAML and OAUTH2, this is the provider ID (will be supplied by Uplimit to the developer).
    */
    'customAuthenticationMethodProviderId': string;
    /**
    * The unique identity for the authentication method. For SAML, this is the SAML entity ID. For OAUTH2, this is the subject identifier (or sub).
    */
    'authenticationSecret': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "emailAddress",
            "baseName": "emailAddress",
            "type": "string"
        },
        {
            "name": "authenticationMethod",
            "baseName": "authenticationMethod",
            "type": "AddUserAuthenticationMethodSchema.AuthenticationMethodEnum"
        },
        {
            "name": "customAuthenticationMethodProviderId",
            "baseName": "customAuthenticationMethodProviderId",
            "type": "string"
        },
        {
            "name": "authenticationSecret",
            "baseName": "authenticationSecret",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AddUserAuthenticationMethodSchema.attributeTypeMap;
    }
}

export namespace AddUserAuthenticationMethodSchema {
    export enum AuthenticationMethodEnum {
        Saml = <any> 'SAML',
        Oauth2 = <any> 'OAUTH2'
    }
}
