/**
 * Uplimit Organization API
 * This API is used to manage organizations within the Uplimit platform. For more information, please reach out to your Uplimit Enterprise contact.
 *
 * The version of the OpenAPI document: 2025-03-07
 * Contact: hello@uplimit.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { V1ListSessionsInCourseGet200ResponseSessionsInner } from './v1ListSessionsInCourseGet200ResponseSessionsInner';

export class ListSessionsInCourseResponseSchema {
    'sessions': Array<V1ListSessionsInCourseGet200ResponseSessionsInner>;
    'totalCount': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "sessions",
            "baseName": "sessions",
            "type": "Array<V1ListSessionsInCourseGet200ResponseSessionsInner>"
        },
        {
            "name": "totalCount",
            "baseName": "totalCount",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ListSessionsInCourseResponseSchema.attributeTypeMap;
    }
}

