/**
 * Uplimit Organization API
 * This API is used to manage organizations within the Uplimit platform. For more information, please reach out to your Uplimit Enterprise contact.
 *
 * The version of the OpenAPI document: 2025-08-11
 * Contact: hello@uplimit.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class UplimitUserInformationSchema {
    /**
    * The email address of the user.
    */
    'emailAddress': string;
    /**
    * The first name of the user.
    */
    'firstName': string;
    /**
    * The last name of the user.
    */
    'lastName': string;
    /**
    * Whether the user is allowed to access the Uplimit platform.
    */
    'userAccountIsActive': boolean;
    /**
    * Whether the user is activated in your organization.
    */
    'userHasValidSubscriptionEnrollment': boolean;
    /**
    * Internal ID to identify the user\'s membership within your organization on Uplimit.
    */
    'uplimitSubscriptionEnrollmentId': string;
    /**
    * Internal ID to identify the \"group\" the user belongs to within your organization. Leaving this blank will enroll the user into the default group.
    */
    'uplimitSubscriptionCommitmentId': string;
    /**
    * All the active subscription commitment ids for this user within this organization.
    */
    'uplimitActiveSubscriptionCommitmentIds': Array<string>;
    /**
    * Internal ID to identify the user across the Uplimit platform.
    */
    'uplimitUserId': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "emailAddress",
            "baseName": "emailAddress",
            "type": "string"
        },
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string"
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string"
        },
        {
            "name": "userAccountIsActive",
            "baseName": "userAccountIsActive",
            "type": "boolean"
        },
        {
            "name": "userHasValidSubscriptionEnrollment",
            "baseName": "userHasValidSubscriptionEnrollment",
            "type": "boolean"
        },
        {
            "name": "uplimitSubscriptionEnrollmentId",
            "baseName": "uplimitSubscriptionEnrollmentId",
            "type": "string"
        },
        {
            "name": "uplimitSubscriptionCommitmentId",
            "baseName": "uplimitSubscriptionCommitmentId",
            "type": "string"
        },
        {
            "name": "uplimitActiveSubscriptionCommitmentIds",
            "baseName": "uplimitActiveSubscriptionCommitmentIds",
            "type": "Array<string>"
        },
        {
            "name": "uplimitUserId",
            "baseName": "uplimitUserId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UplimitUserInformationSchema.attributeTypeMap;
    }
}

