/**
 * Uplimit Organization API
 * This API is used to manage organizations within the Uplimit platform. For more information, please reach out to your Uplimit Enterprise contact.
 *
 * The version of the OpenAPI document: 2025-08-18
 * Contact: hello@uplimit.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class V1GetLearnerActivityStartPostRequest {
    /**
    * The IDs of the sessions to export activity for. If not provided, all sessions will be exported.
    */
    'sessionIds'?: Array<string>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "sessionIds",
            "baseName": "sessionIds",
            "type": "Array<string>"
        }    ];

    static getAttributeTypeMap() {
        return V1GetLearnerActivityStartPostRequest.attributeTypeMap;
    }
}

