/**
 * Uplimit Organization API
 * This API is used to manage organizations within the Uplimit platform. For more information, please reach out to your Uplimit Enterprise contact.
 *
 * The version of the OpenAPI document: 2025-08-18
 * Contact: hello@uplimit.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class V1ToggleUserActivationPostRequest {
    /**
    * The email address of the user.
    */
    'emailAddress': string;
    /**
    * Whether to set the user as active or inactive.
    */
    'setIsActive': boolean;
    /**
    * (optional) The subscription commitment id to target. If not provided, the user will be activated on the default subscription commitment, or deactivated across all their subscription commitments.
    */
    'subscriptionCommitmentId'?: string;
    /**
    * (optional) Whether to send the welcome email to the user when reactivating them. If not provided, the welcome email will be sent. This option is ignored when deactivating the user.
    */
    'doNotSendWelcomeEmail'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "emailAddress",
            "baseName": "emailAddress",
            "type": "string"
        },
        {
            "name": "setIsActive",
            "baseName": "setIsActive",
            "type": "boolean"
        },
        {
            "name": "subscriptionCommitmentId",
            "baseName": "subscriptionCommitmentId",
            "type": "string"
        },
        {
            "name": "doNotSendWelcomeEmail",
            "baseName": "doNotSendWelcomeEmail",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return V1ToggleUserActivationPostRequest.attributeTypeMap;
    }
}

