# coding: utf-8

# flake8: noqa

"""
    Uplimit Organization API

    This API is used to manage organizations within the Uplimit platform. For more information, please reach out to your Uplimit Enterprise contact.

    The version of the OpenAPI document: 2025-08-11
    Contact: hello@uplimit.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "CourseApi",
    "EnrollmentApi",
    "ExportApi",
    "PlatformApi",
    "SessionApi",
    "UserApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AddUserAuthenticationMethodResponseSchema",
    "AddUserAuthenticationMethodSchema",
    "CreateUserResponseSchema",
    "CreateUserSchema",
    "EnrollUserIntoCourseSchema",
    "EnrollUserIntoSessionSchema",
    "GetLearnerActivityGetResponseSchema",
    "GetLearnerActivityStartResponseSchema",
    "HealthcheckIncorrectApiKeyResponseSchema",
    "HealthcheckSuccessResponseSchema",
    "ListActiveUsersResponseSchema",
    "ListCoursesResponseSchema",
    "ListEnrollmentsInSessionResponseSchema",
    "ListInactiveUsersResponseSchema",
    "ListSessionsInCourseResponseSchema",
    "ToggleUserActivationSchema",
    "UnenrollUserFromSessionSchema",
    "UplimitCourseInformationSchema",
    "UplimitSessionInformationSchema",
    "UplimitUserInformationSchema",
    "UplimitUserInformationWithSessionCompletionStatusSchema",
    "V1AddUserAuthenticationMethodPostRequest",
    "V1CreateUserPost200Response",
    "V1CreateUserPost400Response",
    "V1CreateUserPostRequest",
    "V1EnrollUserIntoCoursePostRequest",
    "V1EnrollUserIntoSessionPost200Response",
    "V1EnrollUserIntoSessionPostRequest",
    "V1GetLearnerActivityGetGet200Response",
    "V1GetLearnerActivityStartPost200Response",
    "V1GetLearnerActivityStartPostRequest",
    "V1GetUserInformationEmailAddressOrUserIdGet200Response",
    "V1HealthcheckGet200Response",
    "V1HealthcheckGet403Response",
    "V1ListActiveUsersGet200Response",
    "V1ListCoursesGet200Response",
    "V1ListCoursesGet200ResponseCoursesInner",
    "V1ListEnrollmentsInSessionGet200Response",
    "V1ListEnrollmentsInSessionGet200ResponseUsersInner",
    "V1ListSessionsInCourseGet200Response",
    "V1ListSessionsInCourseGet200ResponseSessionsInner",
    "V1ToggleUserActivationPostRequest",
    "V1UnenrollUserFromSessionPostRequest",
]

# import apis into sdk package
from openapi_client.api.course_api import CourseApi as CourseApi
from openapi_client.api.enrollment_api import EnrollmentApi as EnrollmentApi
from openapi_client.api.export_api import ExportApi as ExportApi
from openapi_client.api.platform_api import PlatformApi as PlatformApi
from openapi_client.api.session_api import SessionApi as SessionApi
from openapi_client.api.user_api import UserApi as UserApi

# import ApiClient
from openapi_client.api_response import ApiResponse as ApiResponse
from openapi_client.api_client import ApiClient as ApiClient
from openapi_client.configuration import Configuration as Configuration
from openapi_client.exceptions import OpenApiException as OpenApiException
from openapi_client.exceptions import ApiTypeError as ApiTypeError
from openapi_client.exceptions import ApiValueError as ApiValueError
from openapi_client.exceptions import ApiKeyError as ApiKeyError
from openapi_client.exceptions import ApiAttributeError as ApiAttributeError
from openapi_client.exceptions import ApiException as ApiException

# import models into sdk package
from openapi_client.models.add_user_authentication_method_response_schema import AddUserAuthenticationMethodResponseSchema as AddUserAuthenticationMethodResponseSchema
from openapi_client.models.add_user_authentication_method_schema import AddUserAuthenticationMethodSchema as AddUserAuthenticationMethodSchema
from openapi_client.models.create_user_response_schema import CreateUserResponseSchema as CreateUserResponseSchema
from openapi_client.models.create_user_schema import CreateUserSchema as CreateUserSchema
from openapi_client.models.enroll_user_into_course_schema import EnrollUserIntoCourseSchema as EnrollUserIntoCourseSchema
from openapi_client.models.enroll_user_into_session_schema import EnrollUserIntoSessionSchema as EnrollUserIntoSessionSchema
from openapi_client.models.get_learner_activity_get_response_schema import GetLearnerActivityGetResponseSchema as GetLearnerActivityGetResponseSchema
from openapi_client.models.get_learner_activity_start_response_schema import GetLearnerActivityStartResponseSchema as GetLearnerActivityStartResponseSchema
from openapi_client.models.healthcheck_incorrect_api_key_response_schema import HealthcheckIncorrectApiKeyResponseSchema as HealthcheckIncorrectApiKeyResponseSchema
from openapi_client.models.healthcheck_success_response_schema import HealthcheckSuccessResponseSchema as HealthcheckSuccessResponseSchema
from openapi_client.models.list_active_users_response_schema import ListActiveUsersResponseSchema as ListActiveUsersResponseSchema
from openapi_client.models.list_courses_response_schema import ListCoursesResponseSchema as ListCoursesResponseSchema
from openapi_client.models.list_enrollments_in_session_response_schema import ListEnrollmentsInSessionResponseSchema as ListEnrollmentsInSessionResponseSchema
from openapi_client.models.list_inactive_users_response_schema import ListInactiveUsersResponseSchema as ListInactiveUsersResponseSchema
from openapi_client.models.list_sessions_in_course_response_schema import ListSessionsInCourseResponseSchema as ListSessionsInCourseResponseSchema
from openapi_client.models.toggle_user_activation_schema import ToggleUserActivationSchema as ToggleUserActivationSchema
from openapi_client.models.unenroll_user_from_session_schema import UnenrollUserFromSessionSchema as UnenrollUserFromSessionSchema
from openapi_client.models.uplimit_course_information_schema import UplimitCourseInformationSchema as UplimitCourseInformationSchema
from openapi_client.models.uplimit_session_information_schema import UplimitSessionInformationSchema as UplimitSessionInformationSchema
from openapi_client.models.uplimit_user_information_schema import UplimitUserInformationSchema as UplimitUserInformationSchema
from openapi_client.models.uplimit_user_information_with_session_completion_status_schema import UplimitUserInformationWithSessionCompletionStatusSchema as UplimitUserInformationWithSessionCompletionStatusSchema
from openapi_client.models.v1_add_user_authentication_method_post_request import V1AddUserAuthenticationMethodPostRequest as V1AddUserAuthenticationMethodPostRequest
from openapi_client.models.v1_create_user_post200_response import V1CreateUserPost200Response as V1CreateUserPost200Response
from openapi_client.models.v1_create_user_post400_response import V1CreateUserPost400Response as V1CreateUserPost400Response
from openapi_client.models.v1_create_user_post_request import V1CreateUserPostRequest as V1CreateUserPostRequest
from openapi_client.models.v1_enroll_user_into_course_post_request import V1EnrollUserIntoCoursePostRequest as V1EnrollUserIntoCoursePostRequest
from openapi_client.models.v1_enroll_user_into_session_post200_response import V1EnrollUserIntoSessionPost200Response as V1EnrollUserIntoSessionPost200Response
from openapi_client.models.v1_enroll_user_into_session_post_request import V1EnrollUserIntoSessionPostRequest as V1EnrollUserIntoSessionPostRequest
from openapi_client.models.v1_get_learner_activity_get_get200_response import V1GetLearnerActivityGetGet200Response as V1GetLearnerActivityGetGet200Response
from openapi_client.models.v1_get_learner_activity_start_post200_response import V1GetLearnerActivityStartPost200Response as V1GetLearnerActivityStartPost200Response
from openapi_client.models.v1_get_learner_activity_start_post_request import V1GetLearnerActivityStartPostRequest as V1GetLearnerActivityStartPostRequest
from openapi_client.models.v1_get_user_information_email_address_or_user_id_get200_response import V1GetUserInformationEmailAddressOrUserIdGet200Response as V1GetUserInformationEmailAddressOrUserIdGet200Response
from openapi_client.models.v1_healthcheck_get200_response import V1HealthcheckGet200Response as V1HealthcheckGet200Response
from openapi_client.models.v1_healthcheck_get403_response import V1HealthcheckGet403Response as V1HealthcheckGet403Response
from openapi_client.models.v1_list_active_users_get200_response import V1ListActiveUsersGet200Response as V1ListActiveUsersGet200Response
from openapi_client.models.v1_list_courses_get200_response import V1ListCoursesGet200Response as V1ListCoursesGet200Response
from openapi_client.models.v1_list_courses_get200_response_courses_inner import V1ListCoursesGet200ResponseCoursesInner as V1ListCoursesGet200ResponseCoursesInner
from openapi_client.models.v1_list_enrollments_in_session_get200_response import V1ListEnrollmentsInSessionGet200Response as V1ListEnrollmentsInSessionGet200Response
from openapi_client.models.v1_list_enrollments_in_session_get200_response_users_inner import V1ListEnrollmentsInSessionGet200ResponseUsersInner as V1ListEnrollmentsInSessionGet200ResponseUsersInner
from openapi_client.models.v1_list_sessions_in_course_get200_response import V1ListSessionsInCourseGet200Response as V1ListSessionsInCourseGet200Response
from openapi_client.models.v1_list_sessions_in_course_get200_response_sessions_inner import V1ListSessionsInCourseGet200ResponseSessionsInner as V1ListSessionsInCourseGet200ResponseSessionsInner
from openapi_client.models.v1_toggle_user_activation_post_request import V1ToggleUserActivationPostRequest as V1ToggleUserActivationPostRequest
from openapi_client.models.v1_unenroll_user_from_session_post_request import V1UnenrollUserFromSessionPostRequest as V1UnenrollUserFromSessionPostRequest
