/*
Uplimit Organization API

This API is used to manage organizations within the Uplimit platform. For more information, please reach out to your Uplimit Enterprise contact.

API version: 2025-03-17
Contact: hello@uplimit.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ToggleUserActivationSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ToggleUserActivationSchema{}

// ToggleUserActivationSchema struct for ToggleUserActivationSchema
type ToggleUserActivationSchema struct {
	// The email address of the user.
	EmailAddress string `json:"emailAddress"`
	// Whether to set the user as active or inactive.
	SetIsActive bool `json:"setIsActive"`
}

type _ToggleUserActivationSchema ToggleUserActivationSchema

// NewToggleUserActivationSchema instantiates a new ToggleUserActivationSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewToggleUserActivationSchema(emailAddress string, setIsActive bool) *ToggleUserActivationSchema {
	this := ToggleUserActivationSchema{}
	this.EmailAddress = emailAddress
	this.SetIsActive = setIsActive
	return &this
}

// NewToggleUserActivationSchemaWithDefaults instantiates a new ToggleUserActivationSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewToggleUserActivationSchemaWithDefaults() *ToggleUserActivationSchema {
	this := ToggleUserActivationSchema{}
	return &this
}

// GetEmailAddress returns the EmailAddress field value
func (o *ToggleUserActivationSchema) GetEmailAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EmailAddress
}

// GetEmailAddressOk returns a tuple with the EmailAddress field value
// and a boolean to check if the value has been set.
func (o *ToggleUserActivationSchema) GetEmailAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EmailAddress, true
}

// SetEmailAddress sets field value
func (o *ToggleUserActivationSchema) SetEmailAddress(v string) {
	o.EmailAddress = v
}

// GetSetIsActive returns the SetIsActive field value
func (o *ToggleUserActivationSchema) GetSetIsActive() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.SetIsActive
}

// GetSetIsActiveOk returns a tuple with the SetIsActive field value
// and a boolean to check if the value has been set.
func (o *ToggleUserActivationSchema) GetSetIsActiveOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SetIsActive, true
}

// SetSetIsActive sets field value
func (o *ToggleUserActivationSchema) SetSetIsActive(v bool) {
	o.SetIsActive = v
}

func (o ToggleUserActivationSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ToggleUserActivationSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["emailAddress"] = o.EmailAddress
	toSerialize["setIsActive"] = o.SetIsActive
	return toSerialize, nil
}

func (o *ToggleUserActivationSchema) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"emailAddress",
		"setIsActive",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varToggleUserActivationSchema := _ToggleUserActivationSchema{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varToggleUserActivationSchema)

	if err != nil {
		return err
	}

	*o = ToggleUserActivationSchema(varToggleUserActivationSchema)

	return err
}

type NullableToggleUserActivationSchema struct {
	value *ToggleUserActivationSchema
	isSet bool
}

func (v NullableToggleUserActivationSchema) Get() *ToggleUserActivationSchema {
	return v.value
}

func (v *NullableToggleUserActivationSchema) Set(val *ToggleUserActivationSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableToggleUserActivationSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableToggleUserActivationSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableToggleUserActivationSchema(val *ToggleUserActivationSchema) *NullableToggleUserActivationSchema {
	return &NullableToggleUserActivationSchema{value: val, isSet: true}
}

func (v NullableToggleUserActivationSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableToggleUserActivationSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


