/*
Uplimit Organization API

This API is used to manage organizations within the Uplimit platform. For more information, please reach out to your Uplimit Enterprise contact.

API version: 2025-08-11
Contact: hello@uplimit.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1GetLearnerActivityGetGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1GetLearnerActivityGetGet200Response{}

// V1GetLearnerActivityGetGet200Response struct for V1GetLearnerActivityGetGet200Response
type V1GetLearnerActivityGetGet200Response struct {
	// The URL to download the exported data.
	Url string `json:"url"`
}

type _V1GetLearnerActivityGetGet200Response V1GetLearnerActivityGetGet200Response

// NewV1GetLearnerActivityGetGet200Response instantiates a new V1GetLearnerActivityGetGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1GetLearnerActivityGetGet200Response(url string) *V1GetLearnerActivityGetGet200Response {
	this := V1GetLearnerActivityGetGet200Response{}
	this.Url = url
	return &this
}

// NewV1GetLearnerActivityGetGet200ResponseWithDefaults instantiates a new V1GetLearnerActivityGetGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1GetLearnerActivityGetGet200ResponseWithDefaults() *V1GetLearnerActivityGetGet200Response {
	this := V1GetLearnerActivityGetGet200Response{}
	return &this
}

// GetUrl returns the Url field value
func (o *V1GetLearnerActivityGetGet200Response) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *V1GetLearnerActivityGetGet200Response) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *V1GetLearnerActivityGetGet200Response) SetUrl(v string) {
	o.Url = v
}

func (o V1GetLearnerActivityGetGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1GetLearnerActivityGetGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *V1GetLearnerActivityGetGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1GetLearnerActivityGetGet200Response := _V1GetLearnerActivityGetGet200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1GetLearnerActivityGetGet200Response)

	if err != nil {
		return err
	}

	*o = V1GetLearnerActivityGetGet200Response(varV1GetLearnerActivityGetGet200Response)

	return err
}

type NullableV1GetLearnerActivityGetGet200Response struct {
	value *V1GetLearnerActivityGetGet200Response
	isSet bool
}

func (v NullableV1GetLearnerActivityGetGet200Response) Get() *V1GetLearnerActivityGetGet200Response {
	return v.value
}

func (v *NullableV1GetLearnerActivityGetGet200Response) Set(val *V1GetLearnerActivityGetGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableV1GetLearnerActivityGetGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableV1GetLearnerActivityGetGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1GetLearnerActivityGetGet200Response(val *V1GetLearnerActivityGetGet200Response) *NullableV1GetLearnerActivityGetGet200Response {
	return &NullableV1GetLearnerActivityGetGet200Response{value: val, isSet: true}
}

func (v NullableV1GetLearnerActivityGetGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1GetLearnerActivityGetGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


