/*
Uplimit Organization API

This API is used to manage organizations within the Uplimit platform. For more information, please reach out to your Uplimit Enterprise contact.

API version: 2025-08-18
Contact: hello@uplimit.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AddUserAuthenticationMethodSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AddUserAuthenticationMethodSchema{}

// AddUserAuthenticationMethodSchema struct for AddUserAuthenticationMethodSchema
type AddUserAuthenticationMethodSchema struct {
	// The email address of the user.
	EmailAddress string `json:"emailAddress"`
	// The authentication method to add to the user.
	AuthenticationMethod string `json:"authenticationMethod"`
	// For SAML and OAUTH2, this is the provider ID (will be supplied by Uplimit to the developer).
	CustomAuthenticationMethodProviderId string `json:"customAuthenticationMethodProviderId"`
	// The unique identity for the authentication method. For SAML, this is the SAML entity ID. For OAUTH2, this is the subject identifier (or sub).
	AuthenticationSecret string `json:"authenticationSecret"`
}

type _AddUserAuthenticationMethodSchema AddUserAuthenticationMethodSchema

// NewAddUserAuthenticationMethodSchema instantiates a new AddUserAuthenticationMethodSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAddUserAuthenticationMethodSchema(emailAddress string, authenticationMethod string, customAuthenticationMethodProviderId string, authenticationSecret string) *AddUserAuthenticationMethodSchema {
	this := AddUserAuthenticationMethodSchema{}
	this.EmailAddress = emailAddress
	this.AuthenticationMethod = authenticationMethod
	this.CustomAuthenticationMethodProviderId = customAuthenticationMethodProviderId
	this.AuthenticationSecret = authenticationSecret
	return &this
}

// NewAddUserAuthenticationMethodSchemaWithDefaults instantiates a new AddUserAuthenticationMethodSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAddUserAuthenticationMethodSchemaWithDefaults() *AddUserAuthenticationMethodSchema {
	this := AddUserAuthenticationMethodSchema{}
	return &this
}

// GetEmailAddress returns the EmailAddress field value
func (o *AddUserAuthenticationMethodSchema) GetEmailAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EmailAddress
}

// GetEmailAddressOk returns a tuple with the EmailAddress field value
// and a boolean to check if the value has been set.
func (o *AddUserAuthenticationMethodSchema) GetEmailAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EmailAddress, true
}

// SetEmailAddress sets field value
func (o *AddUserAuthenticationMethodSchema) SetEmailAddress(v string) {
	o.EmailAddress = v
}

// GetAuthenticationMethod returns the AuthenticationMethod field value
func (o *AddUserAuthenticationMethodSchema) GetAuthenticationMethod() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuthenticationMethod
}

// GetAuthenticationMethodOk returns a tuple with the AuthenticationMethod field value
// and a boolean to check if the value has been set.
func (o *AddUserAuthenticationMethodSchema) GetAuthenticationMethodOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthenticationMethod, true
}

// SetAuthenticationMethod sets field value
func (o *AddUserAuthenticationMethodSchema) SetAuthenticationMethod(v string) {
	o.AuthenticationMethod = v
}

// GetCustomAuthenticationMethodProviderId returns the CustomAuthenticationMethodProviderId field value
func (o *AddUserAuthenticationMethodSchema) GetCustomAuthenticationMethodProviderId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CustomAuthenticationMethodProviderId
}

// GetCustomAuthenticationMethodProviderIdOk returns a tuple with the CustomAuthenticationMethodProviderId field value
// and a boolean to check if the value has been set.
func (o *AddUserAuthenticationMethodSchema) GetCustomAuthenticationMethodProviderIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomAuthenticationMethodProviderId, true
}

// SetCustomAuthenticationMethodProviderId sets field value
func (o *AddUserAuthenticationMethodSchema) SetCustomAuthenticationMethodProviderId(v string) {
	o.CustomAuthenticationMethodProviderId = v
}

// GetAuthenticationSecret returns the AuthenticationSecret field value
func (o *AddUserAuthenticationMethodSchema) GetAuthenticationSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuthenticationSecret
}

// GetAuthenticationSecretOk returns a tuple with the AuthenticationSecret field value
// and a boolean to check if the value has been set.
func (o *AddUserAuthenticationMethodSchema) GetAuthenticationSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthenticationSecret, true
}

// SetAuthenticationSecret sets field value
func (o *AddUserAuthenticationMethodSchema) SetAuthenticationSecret(v string) {
	o.AuthenticationSecret = v
}

func (o AddUserAuthenticationMethodSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AddUserAuthenticationMethodSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["emailAddress"] = o.EmailAddress
	toSerialize["authenticationMethod"] = o.AuthenticationMethod
	toSerialize["customAuthenticationMethodProviderId"] = o.CustomAuthenticationMethodProviderId
	toSerialize["authenticationSecret"] = o.AuthenticationSecret
	return toSerialize, nil
}

func (o *AddUserAuthenticationMethodSchema) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"emailAddress",
		"authenticationMethod",
		"customAuthenticationMethodProviderId",
		"authenticationSecret",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAddUserAuthenticationMethodSchema := _AddUserAuthenticationMethodSchema{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAddUserAuthenticationMethodSchema)

	if err != nil {
		return err
	}

	*o = AddUserAuthenticationMethodSchema(varAddUserAuthenticationMethodSchema)

	return err
}

type NullableAddUserAuthenticationMethodSchema struct {
	value *AddUserAuthenticationMethodSchema
	isSet bool
}

func (v NullableAddUserAuthenticationMethodSchema) Get() *AddUserAuthenticationMethodSchema {
	return v.value
}

func (v *NullableAddUserAuthenticationMethodSchema) Set(val *AddUserAuthenticationMethodSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableAddUserAuthenticationMethodSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableAddUserAuthenticationMethodSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAddUserAuthenticationMethodSchema(val *AddUserAuthenticationMethodSchema) *NullableAddUserAuthenticationMethodSchema {
	return &NullableAddUserAuthenticationMethodSchema{value: val, isSet: true}
}

func (v NullableAddUserAuthenticationMethodSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAddUserAuthenticationMethodSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


