/*
Uplimit Organization API

This API is used to manage organizations within the Uplimit platform. For more information, please reach out to your Uplimit Enterprise contact.

API version: 2025-08-18
Contact: hello@uplimit.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetLearnerActivityStartResponseSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetLearnerActivityStartResponseSchema{}

// GetLearnerActivityStartResponseSchema struct for GetLearnerActivityStartResponseSchema
type GetLearnerActivityStartResponseSchema struct {
	// The ID of the job that was started.
	JobId string `json:"jobId"`
}

type _GetLearnerActivityStartResponseSchema GetLearnerActivityStartResponseSchema

// NewGetLearnerActivityStartResponseSchema instantiates a new GetLearnerActivityStartResponseSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetLearnerActivityStartResponseSchema(jobId string) *GetLearnerActivityStartResponseSchema {
	this := GetLearnerActivityStartResponseSchema{}
	this.JobId = jobId
	return &this
}

// NewGetLearnerActivityStartResponseSchemaWithDefaults instantiates a new GetLearnerActivityStartResponseSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetLearnerActivityStartResponseSchemaWithDefaults() *GetLearnerActivityStartResponseSchema {
	this := GetLearnerActivityStartResponseSchema{}
	return &this
}

// GetJobId returns the JobId field value
func (o *GetLearnerActivityStartResponseSchema) GetJobId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value
// and a boolean to check if the value has been set.
func (o *GetLearnerActivityStartResponseSchema) GetJobIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobId, true
}

// SetJobId sets field value
func (o *GetLearnerActivityStartResponseSchema) SetJobId(v string) {
	o.JobId = v
}

func (o GetLearnerActivityStartResponseSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetLearnerActivityStartResponseSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["jobId"] = o.JobId
	return toSerialize, nil
}

func (o *GetLearnerActivityStartResponseSchema) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"jobId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetLearnerActivityStartResponseSchema := _GetLearnerActivityStartResponseSchema{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetLearnerActivityStartResponseSchema)

	if err != nil {
		return err
	}

	*o = GetLearnerActivityStartResponseSchema(varGetLearnerActivityStartResponseSchema)

	return err
}

type NullableGetLearnerActivityStartResponseSchema struct {
	value *GetLearnerActivityStartResponseSchema
	isSet bool
}

func (v NullableGetLearnerActivityStartResponseSchema) Get() *GetLearnerActivityStartResponseSchema {
	return v.value
}

func (v *NullableGetLearnerActivityStartResponseSchema) Set(val *GetLearnerActivityStartResponseSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableGetLearnerActivityStartResponseSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableGetLearnerActivityStartResponseSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetLearnerActivityStartResponseSchema(val *GetLearnerActivityStartResponseSchema) *NullableGetLearnerActivityStartResponseSchema {
	return &NullableGetLearnerActivityStartResponseSchema{value: val, isSet: true}
}

func (v NullableGetLearnerActivityStartResponseSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetLearnerActivityStartResponseSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


