/*
Uplimit Organization API

This API is used to manage organizations within the Uplimit platform. For more information, please reach out to your Uplimit Enterprise contact.

API version: 2025-08-18
Contact: hello@uplimit.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1ListCoursesGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1ListCoursesGet200Response{}

// V1ListCoursesGet200Response struct for V1ListCoursesGet200Response
type V1ListCoursesGet200Response struct {
	Courses []V1ListCoursesGet200ResponseCoursesInner `json:"courses"`
	TotalCount float32 `json:"totalCount"`
}

type _V1ListCoursesGet200Response V1ListCoursesGet200Response

// NewV1ListCoursesGet200Response instantiates a new V1ListCoursesGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ListCoursesGet200Response(courses []V1ListCoursesGet200ResponseCoursesInner, totalCount float32) *V1ListCoursesGet200Response {
	this := V1ListCoursesGet200Response{}
	this.Courses = courses
	this.TotalCount = totalCount
	return &this
}

// NewV1ListCoursesGet200ResponseWithDefaults instantiates a new V1ListCoursesGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ListCoursesGet200ResponseWithDefaults() *V1ListCoursesGet200Response {
	this := V1ListCoursesGet200Response{}
	return &this
}

// GetCourses returns the Courses field value
func (o *V1ListCoursesGet200Response) GetCourses() []V1ListCoursesGet200ResponseCoursesInner {
	if o == nil {
		var ret []V1ListCoursesGet200ResponseCoursesInner
		return ret
	}

	return o.Courses
}

// GetCoursesOk returns a tuple with the Courses field value
// and a boolean to check if the value has been set.
func (o *V1ListCoursesGet200Response) GetCoursesOk() ([]V1ListCoursesGet200ResponseCoursesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Courses, true
}

// SetCourses sets field value
func (o *V1ListCoursesGet200Response) SetCourses(v []V1ListCoursesGet200ResponseCoursesInner) {
	o.Courses = v
}

// GetTotalCount returns the TotalCount field value
func (o *V1ListCoursesGet200Response) GetTotalCount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value
// and a boolean to check if the value has been set.
func (o *V1ListCoursesGet200Response) GetTotalCountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalCount, true
}

// SetTotalCount sets field value
func (o *V1ListCoursesGet200Response) SetTotalCount(v float32) {
	o.TotalCount = v
}

func (o V1ListCoursesGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1ListCoursesGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["courses"] = o.Courses
	toSerialize["totalCount"] = o.TotalCount
	return toSerialize, nil
}

func (o *V1ListCoursesGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"courses",
		"totalCount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1ListCoursesGet200Response := _V1ListCoursesGet200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1ListCoursesGet200Response)

	if err != nil {
		return err
	}

	*o = V1ListCoursesGet200Response(varV1ListCoursesGet200Response)

	return err
}

type NullableV1ListCoursesGet200Response struct {
	value *V1ListCoursesGet200Response
	isSet bool
}

func (v NullableV1ListCoursesGet200Response) Get() *V1ListCoursesGet200Response {
	return v.value
}

func (v *NullableV1ListCoursesGet200Response) Set(val *V1ListCoursesGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ListCoursesGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ListCoursesGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ListCoursesGet200Response(val *V1ListCoursesGet200Response) *NullableV1ListCoursesGet200Response {
	return &NullableV1ListCoursesGet200Response{value: val, isSet: true}
}

func (v NullableV1ListCoursesGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ListCoursesGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


