/*
Uplimit Organization API

This API is used to manage organizations within the Uplimit platform. For more information, please reach out to your Uplimit Enterprise contact.

API version: 2025-08-11
Contact: hello@uplimit.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1GetLearnerActivityStartPost200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1GetLearnerActivityStartPost200Response{}

// V1GetLearnerActivityStartPost200Response struct for V1GetLearnerActivityStartPost200Response
type V1GetLearnerActivityStartPost200Response struct {
	// The ID of the job that was started.
	JobId string `json:"jobId"`
}

type _V1GetLearnerActivityStartPost200Response V1GetLearnerActivityStartPost200Response

// NewV1GetLearnerActivityStartPost200Response instantiates a new V1GetLearnerActivityStartPost200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1GetLearnerActivityStartPost200Response(jobId string) *V1GetLearnerActivityStartPost200Response {
	this := V1GetLearnerActivityStartPost200Response{}
	this.JobId = jobId
	return &this
}

// NewV1GetLearnerActivityStartPost200ResponseWithDefaults instantiates a new V1GetLearnerActivityStartPost200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1GetLearnerActivityStartPost200ResponseWithDefaults() *V1GetLearnerActivityStartPost200Response {
	this := V1GetLearnerActivityStartPost200Response{}
	return &this
}

// GetJobId returns the JobId field value
func (o *V1GetLearnerActivityStartPost200Response) GetJobId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.JobId
}

// GetJobIdOk returns a tuple with the JobId field value
// and a boolean to check if the value has been set.
func (o *V1GetLearnerActivityStartPost200Response) GetJobIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.JobId, true
}

// SetJobId sets field value
func (o *V1GetLearnerActivityStartPost200Response) SetJobId(v string) {
	o.JobId = v
}

func (o V1GetLearnerActivityStartPost200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1GetLearnerActivityStartPost200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["jobId"] = o.JobId
	return toSerialize, nil
}

func (o *V1GetLearnerActivityStartPost200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"jobId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1GetLearnerActivityStartPost200Response := _V1GetLearnerActivityStartPost200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1GetLearnerActivityStartPost200Response)

	if err != nil {
		return err
	}

	*o = V1GetLearnerActivityStartPost200Response(varV1GetLearnerActivityStartPost200Response)

	return err
}

type NullableV1GetLearnerActivityStartPost200Response struct {
	value *V1GetLearnerActivityStartPost200Response
	isSet bool
}

func (v NullableV1GetLearnerActivityStartPost200Response) Get() *V1GetLearnerActivityStartPost200Response {
	return v.value
}

func (v *NullableV1GetLearnerActivityStartPost200Response) Set(val *V1GetLearnerActivityStartPost200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableV1GetLearnerActivityStartPost200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableV1GetLearnerActivityStartPost200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1GetLearnerActivityStartPost200Response(val *V1GetLearnerActivityStartPost200Response) *NullableV1GetLearnerActivityStartPost200Response {
	return &NullableV1GetLearnerActivityStartPost200Response{value: val, isSet: true}
}

func (v NullableV1GetLearnerActivityStartPost200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1GetLearnerActivityStartPost200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


