/*
Uplimit Organization API

This API is used to manage organizations within the Uplimit platform. For more information, please reach out to your Uplimit Enterprise contact.

API version: 2025-03-07
Contact: hello@uplimit.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the GetUplimitSessionIdUsingDoceboSessionCodeResponseSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetUplimitSessionIdUsingDoceboSessionCodeResponseSchema{}

// GetUplimitSessionIdUsingDoceboSessionCodeResponseSchema struct for GetUplimitSessionIdUsingDoceboSessionCodeResponseSchema
type GetUplimitSessionIdUsingDoceboSessionCodeResponseSchema struct {
	UplimitSessionId string `json:"uplimitSessionId"`
	Name string `json:"name"`
	StartsAt time.Time `json:"startsAt"`
}

type _GetUplimitSessionIdUsingDoceboSessionCodeResponseSchema GetUplimitSessionIdUsingDoceboSessionCodeResponseSchema

// NewGetUplimitSessionIdUsingDoceboSessionCodeResponseSchema instantiates a new GetUplimitSessionIdUsingDoceboSessionCodeResponseSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetUplimitSessionIdUsingDoceboSessionCodeResponseSchema(uplimitSessionId string, name string, startsAt time.Time) *GetUplimitSessionIdUsingDoceboSessionCodeResponseSchema {
	this := GetUplimitSessionIdUsingDoceboSessionCodeResponseSchema{}
	this.UplimitSessionId = uplimitSessionId
	this.Name = name
	this.StartsAt = startsAt
	return &this
}

// NewGetUplimitSessionIdUsingDoceboSessionCodeResponseSchemaWithDefaults instantiates a new GetUplimitSessionIdUsingDoceboSessionCodeResponseSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetUplimitSessionIdUsingDoceboSessionCodeResponseSchemaWithDefaults() *GetUplimitSessionIdUsingDoceboSessionCodeResponseSchema {
	this := GetUplimitSessionIdUsingDoceboSessionCodeResponseSchema{}
	return &this
}

// GetUplimitSessionId returns the UplimitSessionId field value
func (o *GetUplimitSessionIdUsingDoceboSessionCodeResponseSchema) GetUplimitSessionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UplimitSessionId
}

// GetUplimitSessionIdOk returns a tuple with the UplimitSessionId field value
// and a boolean to check if the value has been set.
func (o *GetUplimitSessionIdUsingDoceboSessionCodeResponseSchema) GetUplimitSessionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UplimitSessionId, true
}

// SetUplimitSessionId sets field value
func (o *GetUplimitSessionIdUsingDoceboSessionCodeResponseSchema) SetUplimitSessionId(v string) {
	o.UplimitSessionId = v
}

// GetName returns the Name field value
func (o *GetUplimitSessionIdUsingDoceboSessionCodeResponseSchema) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *GetUplimitSessionIdUsingDoceboSessionCodeResponseSchema) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *GetUplimitSessionIdUsingDoceboSessionCodeResponseSchema) SetName(v string) {
	o.Name = v
}

// GetStartsAt returns the StartsAt field value
func (o *GetUplimitSessionIdUsingDoceboSessionCodeResponseSchema) GetStartsAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.StartsAt
}

// GetStartsAtOk returns a tuple with the StartsAt field value
// and a boolean to check if the value has been set.
func (o *GetUplimitSessionIdUsingDoceboSessionCodeResponseSchema) GetStartsAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartsAt, true
}

// SetStartsAt sets field value
func (o *GetUplimitSessionIdUsingDoceboSessionCodeResponseSchema) SetStartsAt(v time.Time) {
	o.StartsAt = v
}

func (o GetUplimitSessionIdUsingDoceboSessionCodeResponseSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetUplimitSessionIdUsingDoceboSessionCodeResponseSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uplimitSessionId"] = o.UplimitSessionId
	toSerialize["name"] = o.Name
	toSerialize["startsAt"] = o.StartsAt
	return toSerialize, nil
}

func (o *GetUplimitSessionIdUsingDoceboSessionCodeResponseSchema) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uplimitSessionId",
		"name",
		"startsAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetUplimitSessionIdUsingDoceboSessionCodeResponseSchema := _GetUplimitSessionIdUsingDoceboSessionCodeResponseSchema{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetUplimitSessionIdUsingDoceboSessionCodeResponseSchema)

	if err != nil {
		return err
	}

	*o = GetUplimitSessionIdUsingDoceboSessionCodeResponseSchema(varGetUplimitSessionIdUsingDoceboSessionCodeResponseSchema)

	return err
}

type NullableGetUplimitSessionIdUsingDoceboSessionCodeResponseSchema struct {
	value *GetUplimitSessionIdUsingDoceboSessionCodeResponseSchema
	isSet bool
}

func (v NullableGetUplimitSessionIdUsingDoceboSessionCodeResponseSchema) Get() *GetUplimitSessionIdUsingDoceboSessionCodeResponseSchema {
	return v.value
}

func (v *NullableGetUplimitSessionIdUsingDoceboSessionCodeResponseSchema) Set(val *GetUplimitSessionIdUsingDoceboSessionCodeResponseSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUplimitSessionIdUsingDoceboSessionCodeResponseSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUplimitSessionIdUsingDoceboSessionCodeResponseSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUplimitSessionIdUsingDoceboSessionCodeResponseSchema(val *GetUplimitSessionIdUsingDoceboSessionCodeResponseSchema) *NullableGetUplimitSessionIdUsingDoceboSessionCodeResponseSchema {
	return &NullableGetUplimitSessionIdUsingDoceboSessionCodeResponseSchema{value: val, isSet: true}
}

func (v NullableGetUplimitSessionIdUsingDoceboSessionCodeResponseSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUplimitSessionIdUsingDoceboSessionCodeResponseSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


