/*
Uplimit Organization API

This API is used to manage organizations within the Uplimit platform. For more information, please reach out to your Uplimit Enterprise contact.

API version: 2025-08-18
Contact: hello@uplimit.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the V1ListEnrollmentsInSessionGet200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1ListEnrollmentsInSessionGet200Response{}

// V1ListEnrollmentsInSessionGet200Response struct for V1ListEnrollmentsInSessionGet200Response
type V1ListEnrollmentsInSessionGet200Response struct {
	Users []V1ListEnrollmentsInSessionGet200ResponseUsersInner `json:"users"`
	TotalCount float32 `json:"totalCount"`
}

type _V1ListEnrollmentsInSessionGet200Response V1ListEnrollmentsInSessionGet200Response

// NewV1ListEnrollmentsInSessionGet200Response instantiates a new V1ListEnrollmentsInSessionGet200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ListEnrollmentsInSessionGet200Response(users []V1ListEnrollmentsInSessionGet200ResponseUsersInner, totalCount float32) *V1ListEnrollmentsInSessionGet200Response {
	this := V1ListEnrollmentsInSessionGet200Response{}
	this.Users = users
	this.TotalCount = totalCount
	return &this
}

// NewV1ListEnrollmentsInSessionGet200ResponseWithDefaults instantiates a new V1ListEnrollmentsInSessionGet200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ListEnrollmentsInSessionGet200ResponseWithDefaults() *V1ListEnrollmentsInSessionGet200Response {
	this := V1ListEnrollmentsInSessionGet200Response{}
	return &this
}

// GetUsers returns the Users field value
func (o *V1ListEnrollmentsInSessionGet200Response) GetUsers() []V1ListEnrollmentsInSessionGet200ResponseUsersInner {
	if o == nil {
		var ret []V1ListEnrollmentsInSessionGet200ResponseUsersInner
		return ret
	}

	return o.Users
}

// GetUsersOk returns a tuple with the Users field value
// and a boolean to check if the value has been set.
func (o *V1ListEnrollmentsInSessionGet200Response) GetUsersOk() ([]V1ListEnrollmentsInSessionGet200ResponseUsersInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Users, true
}

// SetUsers sets field value
func (o *V1ListEnrollmentsInSessionGet200Response) SetUsers(v []V1ListEnrollmentsInSessionGet200ResponseUsersInner) {
	o.Users = v
}

// GetTotalCount returns the TotalCount field value
func (o *V1ListEnrollmentsInSessionGet200Response) GetTotalCount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value
// and a boolean to check if the value has been set.
func (o *V1ListEnrollmentsInSessionGet200Response) GetTotalCountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalCount, true
}

// SetTotalCount sets field value
func (o *V1ListEnrollmentsInSessionGet200Response) SetTotalCount(v float32) {
	o.TotalCount = v
}

func (o V1ListEnrollmentsInSessionGet200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1ListEnrollmentsInSessionGet200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["users"] = o.Users
	toSerialize["totalCount"] = o.TotalCount
	return toSerialize, nil
}

func (o *V1ListEnrollmentsInSessionGet200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"users",
		"totalCount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1ListEnrollmentsInSessionGet200Response := _V1ListEnrollmentsInSessionGet200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1ListEnrollmentsInSessionGet200Response)

	if err != nil {
		return err
	}

	*o = V1ListEnrollmentsInSessionGet200Response(varV1ListEnrollmentsInSessionGet200Response)

	return err
}

type NullableV1ListEnrollmentsInSessionGet200Response struct {
	value *V1ListEnrollmentsInSessionGet200Response
	isSet bool
}

func (v NullableV1ListEnrollmentsInSessionGet200Response) Get() *V1ListEnrollmentsInSessionGet200Response {
	return v.value
}

func (v *NullableV1ListEnrollmentsInSessionGet200Response) Set(val *V1ListEnrollmentsInSessionGet200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ListEnrollmentsInSessionGet200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ListEnrollmentsInSessionGet200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ListEnrollmentsInSessionGet200Response(val *V1ListEnrollmentsInSessionGet200Response) *NullableV1ListEnrollmentsInSessionGet200Response {
	return &NullableV1ListEnrollmentsInSessionGet200Response{value: val, isSet: true}
}

func (v NullableV1ListEnrollmentsInSessionGet200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ListEnrollmentsInSessionGet200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


