/*
Uplimit Organization API

This API is used to manage organizations within the Uplimit platform. For more information, please reach out to your Uplimit Enterprise contact.

API version: 2025-08-11
Contact: hello@uplimit.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the UplimitSessionInformationSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UplimitSessionInformationSchema{}

// UplimitSessionInformationSchema struct for UplimitSessionInformationSchema
type UplimitSessionInformationSchema struct {
	// Internal ID to identify the session across the Uplimit platform.
	UplimitSessionId string `json:"uplimitSessionId"`
	// The name of the session.
	Name string `json:"name"`
	// The start date of the session.
	StartsAt time.Time `json:"startsAt"`
	// Whether the session allows enrollments
	EnrollmentEnabled bool `json:"enrollmentEnabled"`
}

type _UplimitSessionInformationSchema UplimitSessionInformationSchema

// NewUplimitSessionInformationSchema instantiates a new UplimitSessionInformationSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUplimitSessionInformationSchema(uplimitSessionId string, name string, startsAt time.Time, enrollmentEnabled bool) *UplimitSessionInformationSchema {
	this := UplimitSessionInformationSchema{}
	this.UplimitSessionId = uplimitSessionId
	this.Name = name
	this.StartsAt = startsAt
	this.EnrollmentEnabled = enrollmentEnabled
	return &this
}

// NewUplimitSessionInformationSchemaWithDefaults instantiates a new UplimitSessionInformationSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUplimitSessionInformationSchemaWithDefaults() *UplimitSessionInformationSchema {
	this := UplimitSessionInformationSchema{}
	return &this
}

// GetUplimitSessionId returns the UplimitSessionId field value
func (o *UplimitSessionInformationSchema) GetUplimitSessionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UplimitSessionId
}

// GetUplimitSessionIdOk returns a tuple with the UplimitSessionId field value
// and a boolean to check if the value has been set.
func (o *UplimitSessionInformationSchema) GetUplimitSessionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UplimitSessionId, true
}

// SetUplimitSessionId sets field value
func (o *UplimitSessionInformationSchema) SetUplimitSessionId(v string) {
	o.UplimitSessionId = v
}

// GetName returns the Name field value
func (o *UplimitSessionInformationSchema) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UplimitSessionInformationSchema) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UplimitSessionInformationSchema) SetName(v string) {
	o.Name = v
}

// GetStartsAt returns the StartsAt field value
func (o *UplimitSessionInformationSchema) GetStartsAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.StartsAt
}

// GetStartsAtOk returns a tuple with the StartsAt field value
// and a boolean to check if the value has been set.
func (o *UplimitSessionInformationSchema) GetStartsAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartsAt, true
}

// SetStartsAt sets field value
func (o *UplimitSessionInformationSchema) SetStartsAt(v time.Time) {
	o.StartsAt = v
}

// GetEnrollmentEnabled returns the EnrollmentEnabled field value
func (o *UplimitSessionInformationSchema) GetEnrollmentEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.EnrollmentEnabled
}

// GetEnrollmentEnabledOk returns a tuple with the EnrollmentEnabled field value
// and a boolean to check if the value has been set.
func (o *UplimitSessionInformationSchema) GetEnrollmentEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EnrollmentEnabled, true
}

// SetEnrollmentEnabled sets field value
func (o *UplimitSessionInformationSchema) SetEnrollmentEnabled(v bool) {
	o.EnrollmentEnabled = v
}

func (o UplimitSessionInformationSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UplimitSessionInformationSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uplimitSessionId"] = o.UplimitSessionId
	toSerialize["name"] = o.Name
	toSerialize["startsAt"] = o.StartsAt
	toSerialize["enrollmentEnabled"] = o.EnrollmentEnabled
	return toSerialize, nil
}

func (o *UplimitSessionInformationSchema) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uplimitSessionId",
		"name",
		"startsAt",
		"enrollmentEnabled",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUplimitSessionInformationSchema := _UplimitSessionInformationSchema{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUplimitSessionInformationSchema)

	if err != nil {
		return err
	}

	*o = UplimitSessionInformationSchema(varUplimitSessionInformationSchema)

	return err
}

type NullableUplimitSessionInformationSchema struct {
	value *UplimitSessionInformationSchema
	isSet bool
}

func (v NullableUplimitSessionInformationSchema) Get() *UplimitSessionInformationSchema {
	return v.value
}

func (v *NullableUplimitSessionInformationSchema) Set(val *UplimitSessionInformationSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableUplimitSessionInformationSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableUplimitSessionInformationSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUplimitSessionInformationSchema(val *UplimitSessionInformationSchema) *NullableUplimitSessionInformationSchema {
	return &NullableUplimitSessionInformationSchema{value: val, isSet: true}
}

func (v NullableUplimitSessionInformationSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUplimitSessionInformationSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


