/*
Uplimit Organization API

This API is used to manage organizations within the Uplimit platform. For more information, please reach out to your Uplimit Enterprise contact.

API version: 2025-03-17
Contact: hello@uplimit.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the V1ListSessionsInCourseGet200ResponseSessionsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &V1ListSessionsInCourseGet200ResponseSessionsInner{}

// V1ListSessionsInCourseGet200ResponseSessionsInner struct for V1ListSessionsInCourseGet200ResponseSessionsInner
type V1ListSessionsInCourseGet200ResponseSessionsInner struct {
	// Internal ID to identify the session across the Uplimit platform.
	UplimitSessionId string `json:"uplimitSessionId"`
	// The name of the session.
	Name string `json:"name"`
	// The start date of the session.
	StartsAt time.Time `json:"startsAt"`
}

type _V1ListSessionsInCourseGet200ResponseSessionsInner V1ListSessionsInCourseGet200ResponseSessionsInner

// NewV1ListSessionsInCourseGet200ResponseSessionsInner instantiates a new V1ListSessionsInCourseGet200ResponseSessionsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1ListSessionsInCourseGet200ResponseSessionsInner(uplimitSessionId string, name string, startsAt time.Time) *V1ListSessionsInCourseGet200ResponseSessionsInner {
	this := V1ListSessionsInCourseGet200ResponseSessionsInner{}
	this.UplimitSessionId = uplimitSessionId
	this.Name = name
	this.StartsAt = startsAt
	return &this
}

// NewV1ListSessionsInCourseGet200ResponseSessionsInnerWithDefaults instantiates a new V1ListSessionsInCourseGet200ResponseSessionsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1ListSessionsInCourseGet200ResponseSessionsInnerWithDefaults() *V1ListSessionsInCourseGet200ResponseSessionsInner {
	this := V1ListSessionsInCourseGet200ResponseSessionsInner{}
	return &this
}

// GetUplimitSessionId returns the UplimitSessionId field value
func (o *V1ListSessionsInCourseGet200ResponseSessionsInner) GetUplimitSessionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UplimitSessionId
}

// GetUplimitSessionIdOk returns a tuple with the UplimitSessionId field value
// and a boolean to check if the value has been set.
func (o *V1ListSessionsInCourseGet200ResponseSessionsInner) GetUplimitSessionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UplimitSessionId, true
}

// SetUplimitSessionId sets field value
func (o *V1ListSessionsInCourseGet200ResponseSessionsInner) SetUplimitSessionId(v string) {
	o.UplimitSessionId = v
}

// GetName returns the Name field value
func (o *V1ListSessionsInCourseGet200ResponseSessionsInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *V1ListSessionsInCourseGet200ResponseSessionsInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *V1ListSessionsInCourseGet200ResponseSessionsInner) SetName(v string) {
	o.Name = v
}

// GetStartsAt returns the StartsAt field value
func (o *V1ListSessionsInCourseGet200ResponseSessionsInner) GetStartsAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.StartsAt
}

// GetStartsAtOk returns a tuple with the StartsAt field value
// and a boolean to check if the value has been set.
func (o *V1ListSessionsInCourseGet200ResponseSessionsInner) GetStartsAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.StartsAt, true
}

// SetStartsAt sets field value
func (o *V1ListSessionsInCourseGet200ResponseSessionsInner) SetStartsAt(v time.Time) {
	o.StartsAt = v
}

func (o V1ListSessionsInCourseGet200ResponseSessionsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o V1ListSessionsInCourseGet200ResponseSessionsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uplimitSessionId"] = o.UplimitSessionId
	toSerialize["name"] = o.Name
	toSerialize["startsAt"] = o.StartsAt
	return toSerialize, nil
}

func (o *V1ListSessionsInCourseGet200ResponseSessionsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uplimitSessionId",
		"name",
		"startsAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varV1ListSessionsInCourseGet200ResponseSessionsInner := _V1ListSessionsInCourseGet200ResponseSessionsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varV1ListSessionsInCourseGet200ResponseSessionsInner)

	if err != nil {
		return err
	}

	*o = V1ListSessionsInCourseGet200ResponseSessionsInner(varV1ListSessionsInCourseGet200ResponseSessionsInner)

	return err
}

type NullableV1ListSessionsInCourseGet200ResponseSessionsInner struct {
	value *V1ListSessionsInCourseGet200ResponseSessionsInner
	isSet bool
}

func (v NullableV1ListSessionsInCourseGet200ResponseSessionsInner) Get() *V1ListSessionsInCourseGet200ResponseSessionsInner {
	return v.value
}

func (v *NullableV1ListSessionsInCourseGet200ResponseSessionsInner) Set(val *V1ListSessionsInCourseGet200ResponseSessionsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableV1ListSessionsInCourseGet200ResponseSessionsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableV1ListSessionsInCourseGet200ResponseSessionsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1ListSessionsInCourseGet200ResponseSessionsInner(val *V1ListSessionsInCourseGet200ResponseSessionsInner) *NullableV1ListSessionsInCourseGet200ResponseSessionsInner {
	return &NullableV1ListSessionsInCourseGet200ResponseSessionsInner{value: val, isSet: true}
}

func (v NullableV1ListSessionsInCourseGet200ResponseSessionsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1ListSessionsInCourseGet200ResponseSessionsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


