/*
Uplimit Organization API

This API is used to manage organizations within the Uplimit platform. For more information, please reach out to your Uplimit Enterprise contact.

API version: 2025-03-07
Contact: hello@uplimit.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ListActiveUsersResponseSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListActiveUsersResponseSchema{}

// ListActiveUsersResponseSchema struct for ListActiveUsersResponseSchema
type ListActiveUsersResponseSchema struct {
	Users []V1GetUserInformationEmailAddressOrUserIdGet200Response `json:"users"`
	TotalCount float32 `json:"totalCount"`
}

type _ListActiveUsersResponseSchema ListActiveUsersResponseSchema

// NewListActiveUsersResponseSchema instantiates a new ListActiveUsersResponseSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListActiveUsersResponseSchema(users []V1GetUserInformationEmailAddressOrUserIdGet200Response, totalCount float32) *ListActiveUsersResponseSchema {
	this := ListActiveUsersResponseSchema{}
	this.Users = users
	this.TotalCount = totalCount
	return &this
}

// NewListActiveUsersResponseSchemaWithDefaults instantiates a new ListActiveUsersResponseSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListActiveUsersResponseSchemaWithDefaults() *ListActiveUsersResponseSchema {
	this := ListActiveUsersResponseSchema{}
	return &this
}

// GetUsers returns the Users field value
func (o *ListActiveUsersResponseSchema) GetUsers() []V1GetUserInformationEmailAddressOrUserIdGet200Response {
	if o == nil {
		var ret []V1GetUserInformationEmailAddressOrUserIdGet200Response
		return ret
	}

	return o.Users
}

// GetUsersOk returns a tuple with the Users field value
// and a boolean to check if the value has been set.
func (o *ListActiveUsersResponseSchema) GetUsersOk() ([]V1GetUserInformationEmailAddressOrUserIdGet200Response, bool) {
	if o == nil {
		return nil, false
	}
	return o.Users, true
}

// SetUsers sets field value
func (o *ListActiveUsersResponseSchema) SetUsers(v []V1GetUserInformationEmailAddressOrUserIdGet200Response) {
	o.Users = v
}

// GetTotalCount returns the TotalCount field value
func (o *ListActiveUsersResponseSchema) GetTotalCount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.TotalCount
}

// GetTotalCountOk returns a tuple with the TotalCount field value
// and a boolean to check if the value has been set.
func (o *ListActiveUsersResponseSchema) GetTotalCountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalCount, true
}

// SetTotalCount sets field value
func (o *ListActiveUsersResponseSchema) SetTotalCount(v float32) {
	o.TotalCount = v
}

func (o ListActiveUsersResponseSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListActiveUsersResponseSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["users"] = o.Users
	toSerialize["totalCount"] = o.TotalCount
	return toSerialize, nil
}

func (o *ListActiveUsersResponseSchema) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"users",
		"totalCount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListActiveUsersResponseSchema := _ListActiveUsersResponseSchema{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varListActiveUsersResponseSchema)

	if err != nil {
		return err
	}

	*o = ListActiveUsersResponseSchema(varListActiveUsersResponseSchema)

	return err
}

type NullableListActiveUsersResponseSchema struct {
	value *ListActiveUsersResponseSchema
	isSet bool
}

func (v NullableListActiveUsersResponseSchema) Get() *ListActiveUsersResponseSchema {
	return v.value
}

func (v *NullableListActiveUsersResponseSchema) Set(val *ListActiveUsersResponseSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableListActiveUsersResponseSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableListActiveUsersResponseSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListActiveUsersResponseSchema(val *ListActiveUsersResponseSchema) *NullableListActiveUsersResponseSchema {
	return &NullableListActiveUsersResponseSchema{value: val, isSet: true}
}

func (v NullableListActiveUsersResponseSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListActiveUsersResponseSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


