/*
Uplimit Organization API

This API is used to manage organizations within the Uplimit platform. For more information, please reach out to your Uplimit Enterprise contact.

API version: 2025-03-07
Contact: hello@uplimit.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UplimitCourseInformationSchema type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UplimitCourseInformationSchema{}

// UplimitCourseInformationSchema struct for UplimitCourseInformationSchema
type UplimitCourseInformationSchema struct {
	// Internal ID to identify the course across the Uplimit platform.
	UplimitCourseId string `json:"uplimitCourseId"`
	// The slug (i.e. short name) of the course across the Uplimit platform.
	UplimitCourseSlug string `json:"uplimitCourseSlug"`
	// The name of the course.
	Name string `json:"name"`
}

type _UplimitCourseInformationSchema UplimitCourseInformationSchema

// NewUplimitCourseInformationSchema instantiates a new UplimitCourseInformationSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUplimitCourseInformationSchema(uplimitCourseId string, uplimitCourseSlug string, name string) *UplimitCourseInformationSchema {
	this := UplimitCourseInformationSchema{}
	this.UplimitCourseId = uplimitCourseId
	this.UplimitCourseSlug = uplimitCourseSlug
	this.Name = name
	return &this
}

// NewUplimitCourseInformationSchemaWithDefaults instantiates a new UplimitCourseInformationSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUplimitCourseInformationSchemaWithDefaults() *UplimitCourseInformationSchema {
	this := UplimitCourseInformationSchema{}
	return &this
}

// GetUplimitCourseId returns the UplimitCourseId field value
func (o *UplimitCourseInformationSchema) GetUplimitCourseId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UplimitCourseId
}

// GetUplimitCourseIdOk returns a tuple with the UplimitCourseId field value
// and a boolean to check if the value has been set.
func (o *UplimitCourseInformationSchema) GetUplimitCourseIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UplimitCourseId, true
}

// SetUplimitCourseId sets field value
func (o *UplimitCourseInformationSchema) SetUplimitCourseId(v string) {
	o.UplimitCourseId = v
}

// GetUplimitCourseSlug returns the UplimitCourseSlug field value
func (o *UplimitCourseInformationSchema) GetUplimitCourseSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UplimitCourseSlug
}

// GetUplimitCourseSlugOk returns a tuple with the UplimitCourseSlug field value
// and a boolean to check if the value has been set.
func (o *UplimitCourseInformationSchema) GetUplimitCourseSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UplimitCourseSlug, true
}

// SetUplimitCourseSlug sets field value
func (o *UplimitCourseInformationSchema) SetUplimitCourseSlug(v string) {
	o.UplimitCourseSlug = v
}

// GetName returns the Name field value
func (o *UplimitCourseInformationSchema) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UplimitCourseInformationSchema) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UplimitCourseInformationSchema) SetName(v string) {
	o.Name = v
}

func (o UplimitCourseInformationSchema) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UplimitCourseInformationSchema) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uplimitCourseId"] = o.UplimitCourseId
	toSerialize["uplimitCourseSlug"] = o.UplimitCourseSlug
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *UplimitCourseInformationSchema) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uplimitCourseId",
		"uplimitCourseSlug",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUplimitCourseInformationSchema := _UplimitCourseInformationSchema{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUplimitCourseInformationSchema)

	if err != nil {
		return err
	}

	*o = UplimitCourseInformationSchema(varUplimitCourseInformationSchema)

	return err
}

type NullableUplimitCourseInformationSchema struct {
	value *UplimitCourseInformationSchema
	isSet bool
}

func (v NullableUplimitCourseInformationSchema) Get() *UplimitCourseInformationSchema {
	return v.value
}

func (v *NullableUplimitCourseInformationSchema) Set(val *UplimitCourseInformationSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableUplimitCourseInformationSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableUplimitCourseInformationSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUplimitCourseInformationSchema(val *UplimitCourseInformationSchema) *NullableUplimitCourseInformationSchema {
	return &NullableUplimitCourseInformationSchema{value: val, isSet: true}
}

func (v NullableUplimitCourseInformationSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUplimitCourseInformationSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


