# coding: utf-8

"""
    Uplimit Organization API

    This API is used to manage organizations within the Uplimit platform. For more information, please reach out to your Uplimit Enterprise contact.

    The version of the OpenAPI document: 2025-03-07
    Contact: hello@uplimit.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictStr

class CreateUserResponseSchema(BaseModel):
    """
    CreateUserResponseSchema
    """
    uplimit_subscription_enrollment_id: StrictStr = Field(default=..., alias="uplimitSubscriptionEnrollmentId", description="Internal ID to identify the user's membership within your organization on Uplimit.")
    uplimit_user_id: StrictStr = Field(default=..., alias="uplimitUserId", description="Internal ID to identify the user across the Uplimit platform.")
    __properties = ["uplimitSubscriptionEnrollmentId", "uplimitUserId"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CreateUserResponseSchema:
        """Create an instance of CreateUserResponseSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CreateUserResponseSchema:
        """Create an instance of CreateUserResponseSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CreateUserResponseSchema.parse_obj(obj)

        _obj = CreateUserResponseSchema.parse_obj({
            "uplimit_subscription_enrollment_id": obj.get("uplimitSubscriptionEnrollmentId"),
            "uplimit_user_id": obj.get("uplimitUserId")
        })
        return _obj


