# coding: utf-8

"""
    Uplimit Organization API

    This API is used to manage organizations within the Uplimit platform. For more information, please reach out to your Uplimit Enterprise contact.

    The version of the OpenAPI document: 2025-08-18
    Contact: hello@uplimit.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictStr

class UnenrollUserFromSessionSchema(BaseModel):
    """
    UnenrollUserFromSessionSchema
    """
    email_address: StrictStr = Field(default=..., alias="emailAddress", description="The email address of the user.")
    uplimit_session_id: StrictStr = Field(default=..., alias="uplimitSessionId", description="Internal ID to identify the session across the Uplimit platform.")
    __properties = ["emailAddress", "uplimitSessionId"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> UnenrollUserFromSessionSchema:
        """Create an instance of UnenrollUserFromSessionSchema from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> UnenrollUserFromSessionSchema:
        """Create an instance of UnenrollUserFromSessionSchema from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return UnenrollUserFromSessionSchema.parse_obj(obj)

        _obj = UnenrollUserFromSessionSchema.parse_obj({
            "email_address": obj.get("emailAddress"),
            "uplimit_session_id": obj.get("uplimitSessionId")
        })
        return _obj


